### ISSUE TITLE
Rocketchat

### ISSUE THREAD

**Issue by pjv** [kanboard/plugin-oauth2#14]
Here are the necessary user key mappings for oauth2 via rocketchat (v. 0.74.0):

<img width="335" alt="2019-02-04 at 10 13 am" src="https://user-images.githubusercontent.com/327716/52220910-9b128180-2865-11e9-8ed9-7bd749af6864.png">

This is a working Oauth2 config for me notwithstanding the misspelling of "preferred".

You may wish to update the readme to include this additional example.

**Comment by franckadil** [comment]
@pjv Hi! I tried this setting but I still get the Internal Server Error, I noticed the addition of a user API URL too and the option for account creation, please can you detail how you made it work ?

Cheers,
Franck

**Comment by pjv** [comment]
hi @franckadil I'm really sorry but our team stopped using kanboard and so I took down the instance many months ago. At the time I posted this issue, the config above was working, but I wouldn't be surprised if updates to either kanboard or rocketchat (or both) have changed things in the interim. Sorry I can't help.

**Comment by franckadil** [comment]
@pjv  I understand 👍 thank you for your answer though 💯
