### ISSUE TITLE
Right configuration for mattermost

### ISSUE THREAD

**Issue by DaBlitzStein** [kanboard/plugin-oauth2#2]
I have tried a lot of configurations to use the oauth 2 server from mattermost as source of authentication. What is the right way to configure this?

Thank you in advance.

**Comment by jimscarver** [comment]
I added #7 duplicating this I guess. Did you learn anything?
We need values for:
Scopes
Username Key
Name Key
Email Key
User ID Key

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
