### ISSUE TITLE
How to get the user attributes in a nested json response?

### ISSUE THREAD

**Issue by EdwardNavarro** [kanboard/plugin-oauth2#3]
Hi @fguillot,

How I can get a value of a nested key from a json response? The plugin get only the first level of json response ex:

```javascript
{
  "login": "EdwardNavarro",
  "id": 0987654321,
  "mail": "mail@mail.com",
}
```

But, if my IDP send me the next json response, how i can do to get the "mail" key from the response and use in the plugin setting?

```javascript
{
  "attributes": {
    "cn": [
      "Edward Navarro"
    ],
    "mail": [
      "mail@mail.com"
    ]
  },
  "username": "enavarro"
}
```

Thanks for your help!

**Comment by fguillot** [comment]
The plugin doesn't supports that at the moment. The implementation need to be improved.

For my information, what kind of service did you try to connect to?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
