### ISSUE TITLE
Callback URL displayed incorrectly with Cloudron OAuth

### ISSUE THREAD

**Issue by gramakri** [kanboard/plugin-oauth2#4]
I have testing this plugin with Cloudron OAuth and it works well. One issue is that the Callback URL is incorrect. It displays the port 8000. Kanboard is behind a reverse proxy on the Cloudron. The reverse proxy sets X-Forwarded-Host (test.cloudron.info), X-Forwarded-Proto (https) and X-Forwarded-Ssl (On).

![image](https://cloud.githubusercontent.com/assets/82041/24174398/a2716aba-0e4d-11e7-8881-3a9b9c63c2e1.png)

**Comment by gramakri** [comment]
Note that only the display is incorrect. Removing the "8000" when adding it as Cloudron OAuth Client works perfectly.

**Comment by fguillot** [comment]
Kanboard doesn't read the X-Forwarded-Host header (PR welcome). However, you can still set the application url in settings if Kanboard is not able to guess the proper URL.

**Comment by gramakri** [comment]
@fguillot I can submit a PR but I couldn't figure where that value comes from :) https://github.com/kanboard/plugin-oauth2/blob/master/Template/config/integration.php#L4 wasn't clear to me (sorry, I am not a PHP developer). But any hint as to what it does might help.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
