### ISSUE TITLE
Should allow OAuth2 as only login

### ISSUE THREAD

**Issue by tareko** [kanboard/plugin-oauth2#6]
Hello @fguillot,

I love this plugin. It has helped tremendously. Thank you.

One thing that has come to the fore a bit is that I *only* use OAuth2 for logins. Would it be possible to forward login via OAuth2 only? That is, instead of a small link at the bottom, automatically forward to the result of that link?

This could be an option set in the settings of the plugin.

Thank you,

tarek : )

**Comment by tareko** [comment]
@fguillot Any comments re: the above?

**Comment by fguillot** [comment]
Pull-requests are welcome :) Kanboard itself may have to be modified as well

**Comment by tareko** [comment]
Happy to try for it. Can you point me in any general direction?

**Comment by tareko** [comment]
Hello @fguillot.

After looking at the code, I am running into some problems.

I see that this is [the relevant line](https://github.com/kanboard/plugin-oauth2/blob/master/Plugin.php#L19):

```
        $this->template->hook->attach('template:auth:login-form:after', 'OAuth2:auth/login');
```

However, I cannot tell from the plugin documentation how to *replace* `template:auth:login-form` with `OAuth2:auth/login`. I have tried variations on the following:

```
$this->template->setTemplateOverride('template:auth:login-form', 'OAuth2:auth/login');
```

Any hints?

Thank you,

tarek : )

**Comment by tareko** [comment]
I finally managed this by adding the following to `OAuth2/Template/auth/login.php`:

```
<head>
<meta http-equiv="refresh" content="0; URL=https://task.emlondon.ca/oauth/callback">
<meta name="keywords" content="automatic redirection">
</head>
```

However, this has uncovered another problem that I will file separately, which is that logging out from Kanboard when OAuth2 is used will not automatically activate the logout link for OAuth2.

Ultimately, I disabled the automatic redirect for this reason and put the following in `config.php`:

```
define('HIDE_LOGIN_FORM', true);
```

This remains suboptimal but is an improvement
tarek : )

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
